University of Michigan - ROB 101 Computational Linear Algebra

# Homework 3: Vector and Matrix Multiplication
The Result of a Matrix Multiplication:
$$[n\times k~~\text{matrix}] \cdot [k \times m~~\text{matrix}] = [n \times m~~\text{matrix}].$$

In other words:  In order for the matrix multiplication A times B to be possible, the number of columns in A must equal the number of rows in B.

\begin{equation}
   A \cdot B:= 
\left[\begin{array}{cccc}  a_1^{\rm row} \cdot b_1^{\rm col} & a_1^{\rm row} \cdot b_2^{\rm col} & \cdots & a_1^{\rm row} \cdot b_m^{\rm col} \\
a_2^{\rm row} \cdot b_1^{\rm col} & a_2^{\rm row} \cdot b_2^{\rm col} & \cdots & a_2^{\rm row} \cdot b_m^{\rm col} \\
\vdots & \vdots & \ddots & \vdots \\
a_n^{\rm row} \cdot b_1^{\rm col} & a_n^{\rm row} \cdot b_2^{\rm col} & \cdots & a_n^{\rm row} \cdot b_m^{\rm col}
\end{array}\right].
\end{equation}

### Problem 1.  Rows x Columns
Partition the following matrices, then compute the multiplication product using the formula above.

#### a) $A*B$ where $A = \begin{bmatrix} 3&7&4\\1&4&3\end{bmatrix}$ and $B = \begin{bmatrix}8&3&9&1\\2&4&0&8\\0&7&1&2\end{bmatrix}$

In [17]:
#declare your partitions first
#leave the values as integers or the check below will return a false answer, even if you are right.
a1row = [3 7 4;]
a2row = [1 4 3;] 
b1col = [8; 2; 0;]
b2col = [3; 4; 7;]
b3col = [9; 0; 1;]
b4col = [1; 8; 2;]

#implement code below that computes the product using your partitioned matrices
#your answer should be a 2 x 4 matrix. 
answer1a = [a1row*b1col a1row*b2col a1row*b3col a1row*b4col; a2row *b1col a2row*b2col a2row*b3col a2row*b4col;]

2×4 Matrix{Int64}:
 38  65  31  67
 16  40  12  39

In [14]:
A = [3 7 4; 1 4 3]
B = [8 3 9 1; 2 4 0 8; 0 7 1 2]
check1a = A*B
@assert check1a == answer1a

#### b) $C*D$ where $C = \begin{bmatrix} 7&6&8&7&4\\1&8&2&4&3\\6&9&8&1&4\end{bmatrix}$ and $D = \begin{bmatrix}8&3\\0&4\\7&2\\3&8\\9&2\end{bmatrix}$

In [15]:
#Partition C 
Crow1 = [7 6 8 7 4]
Crow2 = [1 8 2 4 3]
Crow3 = [6 9 8 1 4]

#Partition D
Dcol1 = [8 3;7]
Dcol2 = [3;4;2;8;2]



#Compute product
answer1b = [Crow1*Dcol1 Crow1*Dcol2; Crow2*Dcol1 Crow2*Dcol2; Crow3 *Dcol1 Crow3*Dcol2]

3×2 Matrix{Int64}:
 169  125
  61   77
 143   86

In [ ]:
C = [7 6 8 7 4; 1 8 2 4 3; 6 9 8 1 4]
D = [8 3; 0 4; 7 2; 3 8; 9 2]
check1b = C*D
@assert check1b == answer1b

$$A\cdot B = \sum_{i=1}^{k} a_i^{\rm col} \cdot b_i^{\rm row},  $$
### Problem 2.  Summing over Columns and Rows
Partition the following matrices, then compute the product of matrix multiplication by summing over rows and columns.

#### a.  $F*G$ where $F = \begin{bmatrix}5&1&3\\8&2&0\\1&7&6\\8&2&1\end{bmatrix}$ and $G = \begin{bmatrix}2&4\\8&1\\7&0\end{bmatrix}$

In [19]:
#partition F into columns
Fcol1 = [5; 8; 1; 8;]
Fcol2 = [1; 2; 7; 2;]
Fcol3 = [3; 0; 6; 1;]

#partition G into rows
Grow1 = [2 4]
Grow2 = [8 1]
Grow3 = [7 0]
#compute the product by summing the products of the columns times rows
answer2a =  Fcol1*Grow1 + Fcol2*Grow2 + Fcol3*Grow3

4×2 Matrix{Int64}:
  39  21
  32  34
 100  11
  39  34

In [22]:
F = [5 1 3; 8 2 0; 1 7 6; 8 2 1]
G = [2 4; 8 1; 7 0]
check2a = F*G
@assert check2a == answer2a

#### b.  Using the same matrices, F and G, construct a FOR loop to compute the matrix multiplication $F*G$ like how we did above.
Remember this formula, and how it works:$$A\cdot B = \sum_{i=1}^{k} a_i^{\rm col} \cdot b_i^{\rm row},  $$

Hint: How many times do we have to multiply a column times a row?  What happens to all of the individual column times row matrices at the end?  Keep track of the sum in the for loop so that you don't have to manually sum at the end.

In [28]:
#Declare a matrix of zeros the size of the multiplication product
currentSum = zeros(4,2)
#fill in the number of columns of F (or Rows of G)
n = 3

#the for loop
for i in 1:n
    fCol = F[:, i:i]     #use indexing, and the iterator variable(i) to pick out the column and row to be multiplied
    gRow = G[i:i, :]
    multiplyCxR = fCol*gRow
    currentSum = currentSum + multiplyCxR #update the current sum by adding this round of column by row multiplication
end

answer2b = currentSum

4×2 Matrix{Float64}:
  39.0  21.0
  32.0  34.0
 100.0  11.0
  39.0  34.0

In [ ]:
@assert answer2b == check2a

### The Trick:  Matrix Multiplication is Already Built into Julia
#### You can simply use the * operator to multiply compatible matrices
What?  I did all that for nothing!  No.  By completing the algorithms above, you have followed along the steps that Julia is taking internally. You now understand the inner workings of the computer!

Note: You still need to implement problems 1 and 2 as directed, otherwise you will receive no points on the assignment.

### Problem 3.  Using the * operator
#### Compute $X*Y$ where $X = \begin{bmatrix}8&5&2&1\\6&1&3&2\end{bmatrix}$ and $Y = \begin{bmatrix}4&4&3\\7&6&5\\0&1&3\\9&8&2\end{bmatrix}$

In [29]:
#your code here
X = [8 5 2 1; 6 1 3 2]
Y = [4 4 3; 7 6 5; 0 1 3; 9 8 2]

answer3 =  X * Y

2×3 Matrix{Int64}:
 76  72  57
 49  49  36

In [30]:
X = [8 5 2 1; 6 1 3 2]
Y = [4 4 3; 7 6 5; 0 1 3; 9 8 2]
check3 = X * Y

2×3 Matrix{Int64}:
 76  72  57
 49  49  36

<img src="https://i.postimg.cc/Y0HQcjMM/lu-final.jpg" width="700">

### Problem 4. LU Factorization Step by Step
Follow Algorithm 1 (above), taken from chapter 5 of the course booklet, step by step in Julia, to perform an LU Factorization on Matrix M.
$$ M = \begin{bmatrix}6&5&4\\12&19&14\\24&35&32\end{bmatrix}$$
We are going to do it step by step, just as if you were writing it out as a HW Drill Problem solution. Then, in the next problem, we'll program it up as an honest to goodness algorithm!

In [36]:
# Do all of your work in this cell
# here, we will NOT test that the pivot is non-zero and just hope for the best!
M = [6 5 4; 12 19 14; 24 35 32]
temp=copy(M)
n,m = size(M)
k=1
C=temp[:,k]
pivot=C[k]
C=C/pivot  # Let's hope we do not divide by zero! Yikes!!! 
R=temp[k,:]' # recall, we have to do the transpose in Julia to get a row vector or we use R=temp[k:k,:]
temp = temp-C*R
@show temp
# Run this code now and make sure that temp has a zero first column and a zero first row

# Now its your turn
temp=copy(M)
n,m = size(M)
k=2 
C=temp[:,k]
pivot=C[k]
C=C/pivot  
R=temp[k,:]'
temp = temp-C*R
#you will need to repeat this process n times, where n is the number of rows/columns in M
Temp = copy(M)
L= ArrayFloat64,2(undef,n,0)
U= ArrayFloat64,2(undef,0,n)
Flag = 1;


n=3
for k = 1:n do
C=temp[:,k]
pivot=C[k]
C=C/pivot 
R=temp[k:k,:]'
        if !isapprox(pivot, 0, atol = 1E-8) then
          C= C/pivot  
          temp = temp-C*R  
            L= [L C]
            U= [U; R]
        else
            Flag = 0;
            println("Matrix requires row permutations")
            println("Step where algorithm failed is k=$k")
            return 
        end
        
        end
    return L, U
#Now return L and U
#L = 
#U =

LoadError: MethodError: no method matching *(::Int64, ::Tuple{UndefInitializer, Int64, Int64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at C:\Users\Dusks\AppData\Local\Programs\Julia-1.7.1\share\julia\base\operators.jl:655
  *(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at C:\Users\Dusks\AppData\Local\Programs\Julia-1.7.1\share\julia\base\int.jl:88
  *(::Union{Real, Complex}, ::Union{LinearAlgebra.Adjoint{var"#s859", var"#s8591"}, LinearAlgebra.Transpose{var"#s859", var"#s8591"}} where {var"#s859"<:Union{Real, Complex}, var"#s8591"<:(AbstractVector)}, ::AbstractMatrix{<:Union{Real, Complex}}, ::AbstractMatrix{<:Union{Real, Complex}}) at C:\Users\Dusks\AppData\Local\Programs\Julia-1.7.1\share\julia\stdlib\v1.7\LinearAlgebra\src\matmul.jl:1172
  ...

<img src="https://i.postimg.cc/Y0HQcjMM/lu-final.jpg" width="700">

### Problem 5. LU Factorization in Code
Implement Algorithm 1(above), taken from chapter 5 of the course booklet, in code to perform an LU Factorization on Matrix M.
$$ M = \begin{bmatrix}6&5&4\\12&19&14\\24&35&32\end{bmatrix}$$

Remark: When you first implement the algorithm using a for loop, don't worry about checking that the pivot 
is non-zero. Add that at the very end. 

Next week, we'll show you how to turn your script into a real function so that you can call
 L, U = mylu(M)

In [40]:
#initialization
n,m = size(M)
temp = copy(M)
L = Array{Float64,2}(undef, n, 0)  ~~~\# L=[] Empty matrix\\
U = Array{Float64,2}(undef, 0, n)  ~~~\# R=[] Empty matrix\\
flag = 1
#end intialization

#Your turn! Translate the rest of the algorithm to code here(use a for loop and an if statement)
n=3
for k = 1:n do
C=temp[:,k]
pivot=C[k]
C=C/pivot 
R=temp[k:k,:]';
        if !isapprox(pivot, 0, atol = 1E-8)
          C= C/pivot  
          temp = temp-C*R  
            L= [L C];
            U= [U; R]
        else
            Flag = 0;
            println("Matrix requires row permutations")
            println("Step where algorithm failed is k=$k")
            return 
        end
        
        end
    return L, U





LoadError: MethodError: no method matching ~(::typeof(\))
Closest candidates are:
  ~(::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) at C:\Users\Dusks\AppData\Local\Programs\Julia-1.7.1\share\julia\base\int.jl:310
  ~(::Bool) at C:\Users\Dusks\AppData\Local\Programs\Julia-1.7.1\share\julia\base\bool.jl:37
  ~(::Missing) at C:\Users\Dusks\AppData\Local\Programs\Julia-1.7.1\share\julia\base\missing.jl:101
  ...

In [ ]:
M = [6 5 4; 12 19 14; 24 35 32]
using LinearAlgebra
(low, upp) = lu(M)
@assert low ==L
@assert upp ==U

#### Congratulations! You just translated an algorithm to code.  This is a key skill for a computer or data scientist.

The good news:  Julia has a built in function that will do the LU factorization for you.  Actually, there are two functions. If we use the LinearAlgebra package, we can find the L and U factors by simply typing:
<br> <br>   (L, U) = lu(M, Val(false))

<br> You can also use factorize(M), but it is not reccomended because this multiple dispatch function may return a different type of factorization than an LU. 

Note:  You still need to complete the algorithm above to get points.  It is important that you understand how the algorithm can be done both by hand and by Julia.  Computers exist to make your life easier, but in order for them to do that, you have to understand how they work, and how to use them.

In [ ]:
#LU decomposition without permutations ~Val(false)~
(lower, upper) = lu(M, Val(false))

In [ ]:
#Check that the factorization is correct
lower*upper == M

Note: If you leave off the Val(false) argument, lu() will use permutations, and then $L * U \ne M$


For a more in depth explanation about julia's factorization, visit:
https://julia.quantecon.org/tools_and_techniques/numerical_linear_algebra.html

### Problem 6.  Copy your algorithm from problem 5 into the cell below and run your LU Factorization on a 100 x 100 random matrix


In [ ]:
using Random
N=100
M=rand(N,N)
#copy your algorithm below


In [ ]:
# Check your answer
M-L*U
norm(M-L*U) # We have not covered norms of matrices and vectors yet in lecture, but
            # but you can think of it as a genralized notion of ``length''. 
            # Hence, the norm will be small when all of the entries of the matrix are small
            # A 100 x 100 matrix has 10,000 entries...a bit much to inspect one by one! 